version: '3'

services:
  dev:
    build:
      context: ../Dockerfile
      dockerfile: Dockerfile
    image: fastapi:0.101.0
    container_name: fastapi_authenticate
    volumes:
      - ../src:/app/src
      - ../test:/app/test
      - ../pytest.ini:/app/pytest.ini
    working_dir: /app
    ports:
      - "7870:5000"
    tty: true
    # entrypoint: sh -c "cd /app/src && uvicorn basic_auth:app --host 0.0.0.0 --reload --port 5000"
    entrypoint: sh -c "cd /app/src && uvicorn token_auth:app --host 0.0.0.0 --reload --port 5000"